name: Docker Image Backend

on:
  push:
    branches: [ "main/backend" ]
  pull_request:
    branches: [ "main/backend" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag project_plane_backend:$(date +%s)
